---
name: Documents

on:
  push:
    branches:
      - "**"
    paths:
      - "doc/de/*.md"
      - "doc/en/*.md"
      - "doc/de/images/*"
      - "doc/en/images/*"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  Documents:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.documents.yml@dev
